export const rollerObj = {
    ua: [
        '',
    ],
    ru: [
        '',
    ],
    en: [
        // 'BRO ITS A LOT OF RANDOM TEXT I DONT KNOW WHAT TO WRITE SO I JUST WRITE SOME RANDOM STUFF HERE JUST FOR TESTING AND I PROMISE I WILL DESTROY THIS FUCKING WORLD ANYWAY',
        'THIS IS SOME SYNTRA STUFF HERE I DONT KNOW WANT TEXT HERE BUT ANYWAY',
        'I PROMISE I WILL DESTROY THIS FUCKING WORLD INTO A FUCKING PIECES!',
        'BY THE WAY THIS IS SYNTRA STUFF HERE',
    ]
};